### ISSUE TITLE
[pip install tinkoff-api]

### ISSUE THREAD

**Issue by ghost** [Fatal1ty/tinkoff-api#10]
Привет!
Вылезает ошибка при попытке установить package через pip.
`Requirement already satisfied: pyyaml>=3.13 in ./venv/lib/python3.8/site-packages (from mashumaro<2.0,>=1.12->tinkoff-api) (5.3.1)
Requirement already satisfied: idna>=2.0 in ./venv/lib/python3.8/site-packages (from yarl>=1.4.2->tinkoff-api) (3.0)
Using legacy 'setup.py install' for tinkoff-api, since package 'wheel' is not installed.
Using legacy 'setup.py install' for ciso8601, since package 'wheel' is not installed.
Installing collected packages: ciso8601, aiohttp, tinkoff-api
    Running setup.py install for ciso8601 ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/danilafominyh/Desktop/tinkoff_invest/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/qx/cs3p5gf16ld8jdfczfcv4_2r0000gn/T/pip-install-npyeur95/ciso8601_2f77d31fb3b04bd69ed356480133f7d7/setup.py'"'"'; __file__='"'"'/private/var/folders/qx/cs3p5gf16ld8jdfczfcv4_2r0000gn/T/pip-install-npyeur95/ciso8601_2f77d31fb3b04bd69ed356480133f7d7/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/qx/cs3p5gf16ld8jdfczfcv4_2r0000gn/T/pip-record-phyej0m0/install-record.txt --single-version-externally-managed --compile --install-headers /Users/danilafominyh/Desktop/tinkoff_invest/venv/include/site/python3.8/ciso8601
         cwd: /private/var/folders/qx/cs3p5gf16ld8jdfczfcv4_2r0000gn/T/pip-install-npyeur95/ciso8601_2f77d31fb3b04bd69ed356480133f7d7/
    Complete output (17 lines):
    running install
    running build
    running build_py
    package init file 'ciso8601/__init__.py' not found (or not a regular file)
    creating build
    creating build/lib.macosx-10.15-x86_64-3.8
    creating build/lib.macosx-10.15-x86_64-3.8/ciso8601
    copying ciso8601/__init__.pyi -> build/lib.macosx-10.15-x86_64-3.8/ciso8601
    copying ciso8601/py.typed -> build/lib.macosx-10.15-x86_64-3.8/ciso8601
    running build_ext
    building 'ciso8601' extension
    creating build/temp.macosx-10.15-x86_64-3.8
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -DCISO8601_VERSION=2.1.2 -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/Users/danilafominyh/Desktop/tinkoff_invest/venv/include -I/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/include/python3.8 -c module.c -o build/temp.macosx-10.15-x86_64-3.8/module.o
    xcrun: error: active developer path ("/Applications/Xcode.app/Contents/Developer") does not exist
    Use `sudo xcode-select --switch path/to/Xcode.app` to specify the Xcode that you wish to use for command line developer tools, or use `xcode-select --install` to install the standalone command line developer tools.
    See `man xcode-select` for more details.
    error: command 'clang' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/danilafominyh/Desktop/tinkoff_invest/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/qx/cs3p5gf16ld8jdfczfcv4_2r0000gn/T/pip-install-npyeur95/ciso8601_2f77d31fb3b04bd69ed356480133f7d7/setup.py'"'"'; __file__='"'"'/private/var/folders/qx/cs3p5gf16ld8jdfczfcv4_2r0000gn/T/pip-install-npyeur95/ciso8601_2f77d31fb3b04bd69ed356480133f7d7/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/qx/cs3p5gf16ld8jdfczfcv4_2r0000gn/T/pip-record-phyej0m0/install-record.txt --single-version-externally-managed --compile --install-headers /Users/danilafominyh/Desktop/tinkoff_invest/venv/include/site/python3.8/ciso8601 Check the logs for full command output.`

**Comment by Fatal1ty** [comment]
`xcode-select --install`

**Comment by ghost** [comment]
Да, на винде получилось пофиксить установкой Microsoft Visual Studio (или какие-то компоненты этой среды), на маке получилось пофиксить простой установкой Xcode из App Store.
Спасибо за наводящий коммент!!
