### ISSUE TITLE
get_minute_candles [from .. to ..]

### ISSUE THREAD

**Issue by ghost** [Fatal1ty/tinkoff-api#11]
Привет!
Пытаюсь запустить метод get_minute_candles из примера (с небольшоей модификацией).
Проблема: лимит по dt_to (datetime, до которого я хочу получать данные), не срабатывает.
При запуске кода с dt_to=datetime(2015, 1, 1) всё равно получаю абсолютно все свечи вплоть до последней (самой свежей). Вероятно сам что-то делаю не так, по возможности прошу подсказать, как мне получить массив со свечками внутри определенного интервала (при этом dt_from работает как надо).
Подскажите пожалуйста как сделать лимит по dt_to, что бы только до этой даты отгружались данные.

Вот код:

```python
import json
import asyncio
from datetime import datetime
from tinkoff.investments import CandleResolution, TinkoffInvestmentsRESTClient
from tinkoff.investments.utils.historical_data import HistoricalData

with open('tokens.json', 'r') as f:
    json_opened = json.load(f)

real_token = json_opened["real_token"]
sanbox_token = json_opened["sandbox_token"]


candle_array = []


async def get_minute_candles():
    # show 1 minute candles for AAPL in 1 year period of time
    client = TinkoffInvestmentsRESTClient(token=real_token)
    historical_data = HistoricalData(client)
    start_date = datetime(2020, 12, 1)
    end_date = datetime(2020, 12, 20)
    async for candle in historical_data.iter_candles(
        figi='BBG000B9XRY4',
        dt_from=start_date,
        dt_to=end_date,
        interval=CandleResolution.WEEK,
    ):
        print(candle)
        print(candle.time)
        print(end_date)
        candle_array.append(candle)
        

asyncio.run(get_minute_candles())
```

Вот вывод:

_(venv) MacBook-Pro-Danila:tinkoff_invest danilafominyh$ /Users/danilafominyh/Desktop/tinkoff_invest/venv/bin/python3 /Users/danilafominyh/Desktop/tinkoff_invest/get_candles.py
Candle(figi='BBG000B9XRY4', interval=<CandleResolution.WEEK: 'week'>, o=123.2, c=122.41, h=125.95, l=120.01, v=112212831, time=ISODateTime(2020, 12, 7, 7, 0, tzinfo=datetime.timezone.utc))
2020-12-07 07:00:00+00:00
2020-12-20 00:00:00
Candle(figi='BBG000B9XRY4', interval=<CandleResolution.WEEK: 'week'>, o=122.81, c=126.66, h=129.56, l=121.66, v=203499722, time=ISODateTime(2020, 12, 14, 7, 0, tzinfo=datetime.timezone.utc))
2020-12-14 07:00:00+00:00
2020-12-20 00:00:00
Candle(figi='BBG000B9XRY4', interval=<CandleResolution.WEEK: 'week'>, o=127.6, c=131.97, h=134.4, l=123.12, v=91914082, time=ISODateTime(2020, 12, 21, 7, 0, tzinfo=datetime.timezone.utc))
2020-12-21 07:00:00+00:00
2020-12-20 00:00:00
Candle(figi='BBG000B9XRY4', interval=<CandleResolution.WEEK: 'week'>, o=133.1, c=132.69, h=138.78, l=131.73, v=88446538, time=ISODateTime(2020, 12, 28, 7, 0, tzinfo=datetime.timezone.utc))
2020-12-28 07:00:00+00:00
2020-12-20 00:00:00
Candle(figi='BBG000B9XRY4', interval=<CandleResolution.WEEK: 'week'>, o=132.99, c=128.21, h=135.0, l=126.78, v=56492318, time=ISODateTime(2021, 1, 4, 7, 0, tzinfo=datetime.timezone.utc))
2021-01-04 07:00:00+00:00
2020-12-20 00:00:00
(venv) MacBook-Pro-Danila:tinkoff_invest danilafominyh$ /Users/danilafominyh/Desktop/tinkoff_invest/venv/bin/python3 /Users/danilafominyh/Desktop/tinkoff_invest/get_candles.py
Candle(figi='BBG000B9XRY4', interval=<CandleResolution.WEEK: 'week'>, o=123.2, c=122.41, h=125.95, l=120.01, v=112212831, time=ISODateTime(2020, 12, 7, 7, 0, tzinfo=datetime.timezone.utc))
2020-12-07 07:00:00+00:00
2020-12-20 00:00:00
Candle(figi='BBG000B9XRY4', interval=<CandleResolution.WEEK: 'week'>, o=122.81, c=126.66, h=129.56, l=121.66, v=203499722, time=ISODateTime(2020, 12, 14, 7, 0, tzinfo=datetime.timezone.utc))
2020-12-14 07:00:00+00:00
2020-12-20 00:00:00
Candle(figi='BBG000B9XRY4', interval=<CandleResolution.WEEK: 'week'>, o=127.6, c=131.97, h=134.4, l=123.12, v=91914082, time=ISODateTime(2020, 12, 21, 7, 0, tzinfo=datetime.timezone.utc))
2020-12-21 07:00:00+00:00
2020-12-20 00:00:00
Candle(figi='BBG000B9XRY4', interval=<CandleResolution.WEEK: 'week'>, o=133.1, c=132.69, h=138.78, l=131.73, v=88446538, time=ISODateTime(2020, 12, 28, 7, 0, tzinfo=datetime.timezone.utc))
2020-12-28 07:00:00+00:00
2020-12-20 00:00:00
Candle(figi='BBG000B9XRY4', interval=<CandleResolution.WEEK: 'week'>, o=132.99, c=128.12, h=135.0, l=126.78, v=56492862, time=ISODateTime(2021, 1, 4, 7, 0, tzinfo=datetime.timezone.utc))
2021-01-04 07:00:00+00:00
2020-12-20 00:00:00_

За ранее спасибо!

**Comment by Fatal1ty** [comment]
Попробуй версию 1.12.2

**Comment by ghost** [comment]
Сработало!!! Огромное спасибо!!
