### ISSUE TITLE
TinkoffInvestmentsUnavailableError при вызове client.portfolio.get_positions()

### ISSUE THREAD

**Issue by zkid18** [Fatal1ty/tinkoff-api#12]
Добрый день, ловлю 500 ошибку, когда пытаюсь сделать простой запрос, чтобы получить информацию о портфеле:
Подозреваю, что ошибка возникает из-за того, что не передаю `brokerAccountId`. 
Я правильно понмаю, что работая в Sandbox, я не могу получить доспут на чтение своего порфтеля? Иначе говоря - Sandbox токен позвоялет создать только тестовый брокерский аккаунт, с которым можно эксперементировать.

Код на всякий случай.

```
import asyncio
from datetime import datetime

from tinkoff.investments import (
    TinkoffInvestmentsRESTClient, Environment, PortfolioPosition
)

from tinkoff.investments.client.exceptions import TinkoffInvestmentsError


TOKEN = os.environ['SANDBOX_API']

async def show_your_portfolio():
    async with TinkoffInvestmentsRESTClient(token=TOKEN,environment=Environment.SANDBOX) as client:
        positions = await client.portfolio.get_positions()
        for position in positions:
            print(f'{position.name}: {position.lots} lots')
```

**Comment by Fatal1ty** [comment]
> Подозреваю, что ошибка возникает из-за того, что не передаю `brokerAccountId`.

Если не указывать `brokerAccountId`, то будет использоваться аккаунт по умолчанию. Для песочницы аккаунтом по умолчанию будет тот, который вы зарегистрировали через вызов `client.sandbox.accounts.register()`
> Я правильно понмаю, что работая в Sandbox, я не могу получить доспут на чтение своего порфтеля?

Если речь идет про доступ к портфелю в среде Production, то верно. К портфелю в среде Sandbox можете получить доступ.

> Sandbox токен позвоялет создать только тестовый брокерский аккаунт, с которым можно эксперементировать.

Все так, да.

Резюмируя, создайте аккаунт в песочнице через `client.sandbox.accounts.register()` перед тем как получать портфель. API отдает 500, если аккаунта нет.

**Comment by zkid18** [comment]
Понял, спасибо! 
Мне тогда нужна боевая среда
