### ISSUE TITLE
Цена закрытия отличается от внешних источников

### ISSUE THREAD

**Issue by na88git** [Fatal1ty/tinkoff-api#14]
Добрый день! Подскажите пожалуйста, при запросе можно получить цену закрытия по любому из инструментов. Но тинькофф API возаращает какую то странную цифру. Она не соотвествует реальным данным. Мб вы знаете какой то внешний API по которому можно было бы по figi или isin также как в Тиькофф получать цену закрытия (цена последней с делки, с которой все перестают работать и идут спать), но чтобы эта цена была реальной, а не как у Тинькофф непойми откуда взявшаяся...

**Comment by Fatal1ty** [comment]
Кажется, вопрос не по адресу :)
