### ISSUE TITLE
Проблема с получением свечей по временному интервалу

### ISSUE THREAD

**Issue by xeonvs** [Fatal1ty/tinkoff-api#15]
Пытаюсь получить свечи следующим кодом:
` 
start_date =  datetime(2021, 3, 31, 7, 0, 0)
end_date = datetime(2021, 4, 1, 14, 30, 0)

      async for candle in historical_data.iter_candles(
                figi='BBG000BC3BJ2',
                dt_from=start_date,
                dt_to=end_date,
                interval=CandleResolution.MIN_5,
        ):`
получаем всё по текущее время.

Проблема в том, что в данном случае время в dt_to не учитывается, т.к. в  self._client.market.candles.get оно определено как  dt_to=dt_from + timedelta(days=days_increment + delta.days), т.е. фактически округляется в меньшую сторону.

**Comment by igor-i-plotnikov** [comment]
@xeonvs, а до которого округлилось время?

**Comment by xeonvs** [comment]
dt_from = 2021-03-31 07:00:00
dt_to = offset_aware_datetime(dt_to) = end_date 
days = 1
delta = 1 day
dt_to=dt_from + timedelta(days=days_increment + delta.days) = 2021-04-01 07:00:00
и последняя свеча получается 2021-03-31 15:35:00

**Comment by Fatal1ty** [comment]
@xeonvs добавил в правую границу 1 день, теперь нормально отдает свечки в данном случае. Проверьте на версии из мастера, пожалуйста. Может, еще какие случаи проблемные есть :)

**Comment by xeonvs** [comment]
Спасибо. Вроде всё отлично, завтра проверю более детально.
Бывает вот такая штука на сендбокс окружении
`Traceback (most recent call last):
  File "generate_dataset.py", line 199, in <module>
    asyncio.run(fetch_tinkoff_tickers())
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 608, in run_until_complete
    return future.result()
  File "generate_dataset.py", line 85, in fetch_tinkoff_tickers
    async for candle in historical_data.iter_candles(
  File "/usr/local/lib/python3.8/dist-packages/tinkoff/investments/utils/historical_data.py", line 40, in iter_candles
    for candle in await self._client.market.candles.get(
  File "/usr/local/lib/python3.8/dist-packages/tinkoff/investments/api/market.py", line 85, in get
    payload = await self._request(
  File "/usr/local/lib/python3.8/dist-packages/tinkoff/investments/api/base.py", line 25, in _request
    data = await self._client._request(method, path, rate_limit, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tinkoff/investments/client/rest.py", line 69, in _request
    raise TinkoffInvestmentsConnectionError(str(e)) from None
tinkoff.investments.client.exceptions.TinkoffInvestmentsConnectionError: [Errno 104] Connection reset by peer`
Видимо на лимиты нарываюсь, хотя вроде делаю паузы после каждого тикера. Причем возникает далеко не каждый запуск такое.

В качестве идеи есть такое предложение: сделать что-то типа yfinance.download для параллельной загрузки нескольких котировок за один вызов.

**Comment by Fatal1ty** [comment]
> Видимо на лимиты нарываюсь, хотя вроде делаю паузы после каждого тикера. Причем возникает далеко не каждый запуск такое.

Если код не меняли, то там используется лимитер запросов в соответствии с официальными лимитами, поэтому убедитесь, что вы создаете один инстанс `TinkoffInvestmentsRESTClient` и используете его во всех своих запросах. В любом случае, если бы уперлись в лимиты API, то вы получили бы исключение `TinkoffInvestmentsTooManyRequestsError`, которое бы выбросилось при получении 429 от сервера. Я могу допустить, что соединение рвется из-за сетевых проблем или вы довольно много раз игнорировали лимиты.

**Comment by xeonvs** [comment]
> Если код не меняли, то там используется лимитер запросов в соответствии с официальными лимитами, поэтому убедитесь, что вы создаете один инстанс `TinkoffInvestmentsRESTClient` и используете его во всех своих запросах. В любом случае, если бы уперлись в лимиты API, то вы получили бы исключение `TinkoffInvestmentsTooManyRequestsError`, которое бы выбросилось при получении 429 от сервера. Я могу допустить, что соединение рвется из-за сетевых проблем или вы довольно много раз игнорировали лимиты.

Понял. Благодарю за объяснение, действительно инстанс создаётся на каждый тикер.

**Comment by xeonvs** [comment]
Протестировал, всё отлично! Спасибо!

**Comment by Fatal1ty** [comment]
Зарелизил 1.16.
