### ISSUE TITLE
Getting CLOSE values of minutes candles

### ISSUE THREAD

**Issue by Nikkey13** [Fatal1ty/tinkoff-api#18]
Добрый день. Есть возможность получать значения свечив потоке не тиками, а минутными\часовыми и т.д. таймфреймами. При изменении параметра CandleResolution все равно данные в потоке приходят тиками. Спасибо

**Comment by Fatal1ty** [comment]
> минутными\часовыми и т.д

Добрый день. Я правильно понимаю, что вы хотите получать `CandleEvent` раз в минуту / час и т.д.?

**Comment by Nikkey13** [comment]
Да

**Comment by Fatal1ty** [comment]
Такого в API не предусмотрено. Вы можете фильтровать события с одинаковым временем на своей стороне.
