### ISSUE TITLE
Sandbox register method not works. And other sandbox-only methods.

### ISSUE THREAD

**Issue by iksmpro** [Fatal1ty/tinkoff-api#3]
Because path variable for this methods is "path='/sandbox/register',", and if Environment = SANDBOX, base url already contains "/sandbox/" part. The result url is like "https://api-invest.tinkoff.ru/openapi/sandbox/sandbox/register". I guess you dont need "sandbox" word in path.

I dont know how example with sandbox works :)

**Comment by Fatal1ty** [comment]
We need duplicated "sandbox" word in the path because the official API requires it https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/#/sandbox/post_sandbox_register

You can try sandbox methods on your own with or without an extra "sandbox".

**Comment by iksmpro** [comment]
wow. Okay, sorry for this issue.
