### ISSUE TITLE
FIGI vs Tickers

### ISSUE THREAD

**Issue by pdyachen** [Fatal1ty/tinkoff-api#5]
Thanks for the work firstly!
One issue I can't come over is getting all FIGI that I need, when trading or working with market data I use tickers, but API requires FIGI, I need to map one to the other, but I don't see any method for this in the client. How would you recommend to go ?

**Comment by Fatal1ty** [comment]
You can find all instruments with the required ticker in the following way:
```python
from tinkoff.investments import TinkoffInvestmentsRESTClient
client = TinkoffInvestmentsRESTClient(...)
instruments = await client.market.instruments.search('AAPL')
for instrument in instruments:
    print(instrument.figi)
```

If you want to get the instrument by FIGI you should use another method:
```python
from tinkoff.investments import TinkoffInvestmentsRESTClient
client = TinkoffInvestmentsRESTClient(...)
instrument = await client.market.instruments.get('BBG000B9XRY4')
print(instrument.ticker)
```

**Comment by Fatal1ty** [comment]
If you trade a large number of instruments, it's better to get all of them with a method corresponding to the type of the instruments:
```python
stocks = await client.market.instruments.get_stocks()
etfs = await client.market.instruments.get_etfs()
bonds = await client.market.instruments.get_bonds()
currencies = await client.market.instruments.get_currencies()
```
