### ISSUE TITLE
Decimal вместо float для цен

### ISSUE THREAD

**Issue by lobziq** [Fatal1ty/tinkoff-api#7]
привет, предлагаю сменить float на Decimal для ценовых значений на основании вот этого обсуждения
https://stackoverflow.com/questions/3730019/why-not-use-double-or-float-to-represent-currency

я тоже натыкался пару раз на косяки на копеечных акциях типа ВТБ — 0,033605 цена например, но сейчас не могу воспроизвести точный кейс
форкнул и попробовал реализовать сам, но не получается сделать обратную совместимость, чтобы можно было оставить float и не ломать для тех, кто уже сейчас использует либу — проблема в том, что mashumaru десериализует в указанный тип, а Union пока не реализован (если эта фича доедет, то получается изи)

вот я как сделал кастомные декодеры
https://github.com/lobziq/tinkoff-api/blob/master/tinkoff/investments/client/rest.py
https://github.com/lobziq/tinkoff-api/blob/master/tinkoff/investments/client/streaming.py

**Comment by Fatal1ty** [comment]
Без фиксации количества знаков после запятой в модели это не имеет смысла, но у каждого инструмента свой индивидуальный `min_price_increment`, что не позволяет это сделать. Мне кажется, лучше брать из ответа цену во float и далее уже отталкиваясь от `min_price_increment` выполнять корректно арифметические операции и "округление" в каждом конкретном случае. А шаг округления бывает еще и не равен степени десяти.
