### ISSUE TITLE
Ослабьте требования к зависимостям

### ISSUE THREAD

**Issue by espdev** [Fatal1ty/tinkoff-api#8]
Привет.

Сейчас в вашем пакете диапазоны версий пакетов зависимостей заданы достаточно жестко, при этом версии некоторых пакетов уже устарели:

https://github.com/Fatal1ty/tinkoff-api/blob/8ade1947af20287248a2f085a2afc8f2741eb4d5/setup.py#L36-L41

Из-за этого возникают проблемы с использованием вашего пакета в проектах. Например, я использую poetry для управления зависимостями, и мой проект зависит от aiohttp 3.7.3 (текущая версия на этот момент). Я не могу добавить ваш пакет в свой проект, потому что у вас aiohttp ограничен `<3.7` и возникает конфликт разрешения версий зависимостей, хотя для такого ограничения нет никаких видимых причин. Вы могли бы сделать для aiohttp верхнее ограничение, например `<4`.

Версии для yarl вообще можно не указывать, потому что от него зависит aiohttp.

**Comment by Fatal1ty** [comment]
Справедливо. Сейчас уберу такие жесткие ограничения на aiohttp. Зависимость yarl оставлю на случай, если aiohttp уйдет от его использования, а в tinkoff-api он используется.

**Comment by Fatal1ty** [comment]
Ослабил в 1.11.

**Comment by espdev** [comment]
@Fatal1ty спасибо!
