### ISSUE TITLE
Try to get Historical data [TinkoffInvestmentsUnavailableError]

### ISSUE THREAD

**Issue by WurgBASH** [Fatal1ty/tinkoff-api#9]
Здравствуйте, запускаю [пример get_minute_candles](https://github.com/Fatal1ty/tinkoff-api#historical-data) и не могу запустить его,  у меня код выдает TinkoffInvestmentsUnavailableError. Я попробовал запустить пример Streaming Client, который тоже представлен в главном readme, он у меня запустился и отработал без ошибок. А вот Historical data не получись. Может быть вы знаете в чем, может быть причина? В качестве аргументов я передаю те параметры, что представлены в примерах.

**Comment by Fatal1ty** [comment]
Возможно, у вас токен для песочницы. Если так, то передайте в `TinkoffInvestmentsRESTClient` параметр `environment=Environment.SANDBOX`. Только что проверил, почему-то с токеном от песочницы прод отдает пятисотку.

**Comment by WurgBASH** [comment]
Сработало, спасибо вам большое)
